# Generated by Django 3.2.7 on 2021-10-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
