# Generated by Django 3.2.7 on 2021-11-17 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("user", "0002_delete_passenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="token",
            field=models.CharField(default=django.utils.timezone.now, max_length=36),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Driver",),
    ]
