# Generated by Django 3.2.7 on 2021-09-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('trip_date', models.DateTimeField(verbose_name='trip date')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
