# Generated by Django 3.2.7 on 2021-10-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrip',
            name='trip_date',
            field=models.CharField(max_length=200),
        ),
    ]
